source "https://rubygems.org"

gem "sinatra", "~>2.2.0"
gem "sinatra-contrib"
gem "erubis"
gem "rack", ">= 1.6.12"
gem "rack-protection", ">= 1.5.5"
gem "redcarpet"
gem "bcrypt"

gem "rack-test"
gem "minitest"

ruby "~> 2.6.2"
